name: "Klessens Bouw"
description: "Some cool description"

year: 2024

brand:
  logo: "/img/kbt-logo.svg"
  name: "Klessens Bouw"

email: info@klessensbouw.nl
phone: +31 132 032 856

address:
  street: Pannenschuurlaan 68
  zipcode: 5061 DT
  city: Oisterwijk

kvk_nummer: 66713943

socials:
  - name: facebook
    icon: facebook
    url: "https://www.facebook.com/klessensbouw/"
  - name: youtube
    icon: youtube
    url: "https://www.youtube.com/@KBT-Oisterwijk/"
