root: "https://klessensbouw.nl"
name: KBT
description: "Uw partner in klussen"

analytics:
  google_id: ""
  umami_id: ""

metas:
  site: =name
  title: =title
  description: =description
  image: =image
  twitter: ""
  lang: en
  generator: true
